<?php

$labels = array();

$labels['signature'] = 'Signatur';
$labels['changesignature'] = 'Signature bearbeiten';

$labels['enabled'] = 'Aktiviert';
$labels['htmlsignature'] = 'HTML Signatur';
$labels['plaintextsignature'] = 'Einfacher Text Signatur';

$messages = array();
$messages['successfullyupdated'] = 'Signatur erfolgreich aktualisiert.';
$messages['internalerror'] = 'Fehler bei der ausgewählten Aktion.';
//$messages['connecterror'] = $messages['internalerror'] . ' Connection error.';
$messages['loaderror'] = 'Signatur konnte nicht geladen werden.';
$messages['loadconnecterror'] = $messages['loadinternalerror'] . ' Connection error.';
$messages['updateerror'] = 'Signatur konnte nicht aktualisiert werden.';
$messages['updateconnecterror'] = $messages['updateerror'] . ' Connection error.';
