<?php

$labels['signature'] = 'Signatur';
$labels['changesignature'] = 'Ändra signatur';

$labels['enabled'] = 'Aktiv';
$labels['htmlsignature'] = 'Signatur i HTML';
$labels['plaintextsignature'] = 'Signatur i klartext';

$messages['successfullyupdated'] = 'Signaturen har uppdaterats.';
$messages['internalerror'] = 'Fel uppstod i vald åtgärd.';
//$messages['connecterror'] = $messages['internalerror'] . ' Uppkopplingsfel.';
$messages['loaderror'] = 'Kunde inte ladda signaturen.';
$messages['loadconnecterror'] = $messages['loadinternalerror'] . ' Uppkopplingsfel.';
$messages['updateerror'] = 'Kunde inte uppdatera signaturen.';
$messages['updateconnecterror'] = $messages['updateerror'] . ' Connection error.';
